import type { Course, GlossaryTerm } from "../types";

const term = (
  english: string,
  chinese: string,
  aliases = "",
  priority = 2,
): GlossaryTerm => ({
  english,
  chinese,
  aliases,
  priority,
  enabled: true,
});

export const CELLULAR_NETWORK_GLOSSARY: GlossaryTerm[] = [
  term("Singtel", "新加坡电信", "Singapore Telecommunications", 3),
  term("StarHub", "星和", "", 3),
  term("M1", "第一通", "", 3),
  term("SIMBA Telecom", "SIMBA 电信", "TPG Singapore", 3),
  term("IMDA", "新加坡资讯通信媒体发展局", "Infocomm Media Development Authority", 3),
  term("NUS", "新加坡国立大学", "National University of Singapore", 3),
  term("Cellular Networks", "蜂窝网络", "cellular network", 3),
  term("Base Transceiver Station", "基站收发台", "BTS", 3),
  term("Base Station Controller", "基站控制器", "BSC", 3),
  term("Mobile Switching Center", "移动交换中心", "MSC", 3),
  term("Base Station Subsystem", "基站子系统", "BSS", 3),
  term("Radio Network Controller", "无线网络控制器", "RNC", 3),
  term("Serving GPRS Support Node", "服务 GPRS 支持节点", "SGSN", 3),
  term("Gateway GPRS Support Node", "网关 GPRS 支持节点", "GGSN", 3),
  term("Radio Access Network", "无线接入网", "RAN", 3),
  term("Public Switched Telephone Network", "公共交换电话网", "PSTN", 3),
  term("Global System for Mobile Communications", "全球移动通信系统", "GSM", 3),
  term("General Packet Radio Service", "通用分组无线业务", "GPRS", 3),
  term("Enhanced Data rates for GSM Evolution", "增强型 GSM 数据速率", "EDGE", 3),
  term("Universal Mobile Telecommunications System", "通用移动通信系统", "UMTS", 3),
  term("High Speed Packet Access", "高速分组接入", "HSPA", 3),
  term("Long Term Evolution", "长期演进", "LTE", 3),
  term("LTE Advanced", "LTE 增强版", "LTE-A", 3),
  term("5G New Radio", "5G 新空口", "5G NR, NR", 3),
  term("Frequency Division Multiple Access", "频分多址", "FDMA", 3),
  term("Time Division Multiple Access", "时分多址", "TDMA", 3),
  term("Code Division Multiple Access", "码分多址", "CDMA", 3),
  term("Orthogonal Frequency Division Multiple Access", "正交频分多址", "OFDMA", 3),
  term("Single Carrier FDMA", "单载波频分多址", "SC-FDMA", 3),
  term("Frequency Division Multiplexing", "频分复用", "FDM", 3),
  term("Frequency Division Duplex", "频分双工", "FDD", 3),
  term("Time Division Duplex", "时分双工", "TDD", 3),
  term("Multiple Input Multiple Output", "多输入多输出", "MIMO", 3),
  term("Grade of Service", "服务等级", "GoS", 3),
  term("Quality of Service", "服务质量", "QoS", 3),
  term("Answer-Seizure Ratio", "应答接通率", "ASR", 3),
  term("Answer-Busy Ratio", "应答忙占比", "ABR", 3),
  term("Busy Hour Call Attempts", "忙时呼叫尝试次数", "BHCA", 3),
  term("Erlang", "爱尔兰", "erl", 3),
  term("Erlang B", "爱尔兰 B 公式", "Erlang-B, Erlang B formula", 3),
  term("Erlang C", "爱尔兰 C 公式", "Erlang-C, Erlang C formula", 3),
  term("Poisson Arrivals See Time Averages", "泊松到达见到时间平均", "PASTA theorem, PASTA", 3),
  term("M/M/1 queue", "M/M/1 排队系统", "M M 1", 3),
  term("M/M/c queue", "M/M/c 排队系统", "M M c", 3),
  term("M/M/1/K queue", "M/M/1/K 有限容量排队系统", "M M 1 K", 3),
  term("M/M/c/c queue", "M/M/c/c 损失系统", "M M c c", 3),
  term("Blocked Call Held", "阻塞呼叫保持", "BCH", 3),
  term("Blocked Call Cleared", "阻塞呼叫清除", "BCC", 3),
  term("Blocked Call Delayed", "阻塞呼叫延迟", "BCD", 3),
  term("Radio Network Planning", "无线网络规划"),
  term("Transmission Network Planning", "传输网络规划"),
  term("Core Network Planning", "核心网规划"),
  term("core network", "核心网"),
  term("base station", "基站", "BS"),
  term("mobile subscriber", "移动用户"),
  term("cell sector", "小区扇区", "sector"),
  term("sectoring", "扇区化"),
  term("directional antenna", "定向天线"),
  term("frequency reuse", "频率复用"),
  term("co-channel interference", "同频干扰", "CCI"),
  term("adjacent-channel interference", "邻频干扰", "ACI"),
  term("handover", "切换", "handoff"),
  term("roaming", "漫游"),
  term("circuit switching", "电路交换"),
  term("packet switching", "分组交换"),
  term("TCP/IP protocol stack", "TCP/IP 协议栈", "TCP IP"),
  term("multiplexing", "复用"),
  term("channel spacing", "信道间隔"),
  term("guard band", "保护频带"),
  term("link budget", "链路预算"),
  term("path loss", "路径损耗"),
  term("shadowing", "阴影衰落"),
  term("multipath fading", "多径衰落"),
  term("Rayleigh fading", "瑞利衰落"),
  term("Rician fading", "莱斯衰落"),
  term("Signal-to-Interference-plus-Noise Ratio", "信干噪比", "SINR"),
  term("Received Signal Strength Indicator", "接收信号强度指示", "RSSI"),
  term("Reference Signal Received Power", "参考信号接收功率", "RSRP"),
  term("Reference Signal Received Quality", "参考信号接收质量", "RSRQ"),
  term("beamforming", "波束赋形"),
  term("spectral efficiency", "频谱效率"),
  term("cell capacity", "小区容量"),
  term("call capacity", "呼叫容量"),
  term("channel requirement modeling", "信道需求建模"),
  term("traffic engineering", "话务工程"),
  term("traffic intensity", "话务强度"),
  term("call intensity", "呼叫强度", "calling rate"),
  term("call holding time", "呼叫保持时间"),
  term("offered load", "提供负载", "offered traffic"),
  term("carried traffic", "承载话务量"),
  term("blocked traffic", "阻塞话务量"),
  term("blocking probability", "阻塞概率"),
  term("trunking", "中继汇接"),
  term("trunking efficiency", "中继效率"),
  term("busy hour", "忙时"),
  term("Average Busy Season Busy Hour", "平均忙季忙时", "ABSBH"),
  term("Poisson distribution", "泊松分布"),
  term("binomial distribution", "二项分布"),
  term("exponential distribution", "指数分布"),
  term("stochastic process", "随机过程"),
  term("stationary process", "平稳过程"),
  term("queueing theory", "排队论", "queuing theory"),
  term("arrival process", "到达过程"),
  term("service process", "服务过程"),
  term("queue discipline", "排队规则"),
  term("inter-arrival time", "到达间隔时间", "interarrival time"),
  term("service time", "服务时间"),
  term("Markovian", "马尔可夫型"),
  term("memoryless property", "无记忆性"),
  term("birth-death process", "生灭过程", "birth and death process"),
  term("stationary distribution", "平稳分布"),
  term("normalization constant", "归一化常数"),
  term("steady-state probability", "稳态概率"),
  term("service utilization factor", "服务利用率", "utilization factor"),
  term("arrival rate", "到达率"),
  term("service rate", "服务率"),
  term("balking", "拒绝进入队列"),
  term("reneging", "中途退出队列"),
  term("First Come First Served", "先到先服务", "FCFS"),
  term("mobile-to-land", "移动到固网", "M2L", 1),
  term("land-to-mobile", "固网到移动", "L2M", 1),
  term("mobile-to-mobile", "移动到移动", "M2M", 1),
  term("Multimedia Messaging Service", "多媒体消息服务", "MMS", 1),
];

export const MACHINE_LEARNING_GLOSSARY: GlossaryTerm[] = [
  term("CEG5301", "机器学习及其应用", "Machine Learning with Applications", 3),
  term("NUS", "新加坡国立大学", "National University of Singapore", 3),
  term("artificial neural network", "人工神经网络", "ANN, neural network", 3),
  term("linear network", "线性网络", "linear networks", 3),
  term("perceptron", "感知机", "single-layer perceptron", 3),
  term("radial basis function network", "径向基函数网络", "RBF network, RBFN", 3),
  term("synaptic weights", "突触权重", "synaptic weight, connection weights", 3),
  term("induced local field", "诱导局部场", "local field", 3),
  term("activation function", "激活函数", "transfer function", 3),
  term("supervised learning", "监督学习", "learning with a teacher", 3),
  term("unsupervised learning", "无监督学习", "self-organized learning", 3),
  term("reinforcement learning", "强化学习", "RL", 3),
  term("operant conditioning", "操作性条件反射", "Skinnerian conditioning", 3),
  term("Skinner box", "斯金纳箱", "operant conditioning chamber", 3),
  term("error signal", "误差信号", "prediction error", 3),
  term("desired output", "期望输出", "target output", 3),
  term("decision boundary", "决策边界", "decision surface", 3),
  term("linearly separable", "线性可分", "linear separability", 3),
  term("learning rate", "学习率", "step size", 3),
  term("backpropagation", "反向传播", "back-propagation, backprop", 3),
  term("gradient descent", "梯度下降", "GD", 3),
  term("stochastic gradient descent", "随机梯度下降", "SGD", 3),
  term("multilayer perceptron", "多层感知机", "MLP", 3),
  term("convolutional neural network", "卷积神经网络", "CNN", 3),
  term("recurrent neural network", "循环神经网络", "RNN", 3),
  term("long short-term memory", "长短期记忆网络", "LSTM", 3),
  term("transformer", "Transformer 模型", "Transformer network", 3),
  term("attention mechanism", "注意力机制", "self-attention", 3),
  term("support vector machine", "支持向量机", "SVM", 3),
  term("kernel-based learning machine", "基于核的学习机", "kernel machine", 3),
  term("principal component analysis", "主成分分析", "PCA", 3),
  term("k-nearest neighbors", "K 近邻", "KNN, k nearest neighbour", 3),
  term("k-means clustering", "K 均值聚类", "k-means", 3),
  term("naive Bayes", "朴素贝叶斯", "naive Bayes classifier", 3),
  term("input vector", "输入向量"),
  term("weight vector", "权重向量"),
  term("bias term", "偏置项", "bias, intercept"),
  term("free parameters", "自由参数", "trainable parameters"),
  term("stimulus", "刺激", "stimuli"),
  term("teacher signal", "教师信号", "supervisory signal"),
  term("reward signal", "奖励信号", "reward, penalty signal"),
  term("Hebbian learning", "赫布学习", "Hebb's rule"),
  term("competitive learning", "竞争学习"),
  term("self-organizing map", "自组织映射", "SOM, Kohonen map"),
  term("forward propagation", "前向传播", "forward pass"),
  term("loss function", "损失函数", "cost function, objective function"),
  term("mean squared error", "均方误差", "MSE"),
  term("cross-entropy loss", "交叉熵损失", "cross entropy"),
  term("sigmoid function", "Sigmoid 函数", "logistic function"),
  term("hyperbolic tangent", "双曲正切", "tanh"),
  term("rectified linear unit", "修正线性单元", "ReLU"),
  term("softmax function", "Softmax 函数", "softmax"),
  term("hidden layer", "隐藏层"),
  term("input layer", "输入层"),
  term("output layer", "输出层"),
  term("epoch", "训练轮次"),
  term("mini-batch", "小批量", "minibatch"),
  term("feature vector", "特征向量"),
  term("feature space", "特征空间"),
  term("pattern recognition", "模式识别"),
  term("constrained optimization", "约束优化"),
  term("training set", "训练集", "training data"),
  term("validation set", "验证集", "validation data"),
  term("test set", "测试集", "test data"),
  term("ground truth", "真实标签", "ground-truth label"),
  term("classification", "分类"),
  term("regression", "回归"),
  term("clustering", "聚类"),
  term("overfitting", "过拟合"),
  term("underfitting", "欠拟合"),
  term("regularization", "正则化"),
  term("L1 regularization", "L1 正则化", "lasso"),
  term("L2 regularization", "L2 正则化", "weight decay, ridge"),
  term("dropout", "Dropout 正则化"),
  term("confusion matrix", "混淆矩阵"),
  term("precision", "精确率"),
  term("recall", "召回率", "sensitivity"),
  term("F1 score", "F1 分数", "F-measure"),
  term("receiver operating characteristic", "受试者工作特征曲线", "ROC curve"),
  term("area under the curve", "曲线下面积", "AUC"),
  term("kernel trick", "核技巧", "kernel method"),
  term("decision tree", "决策树"),
  term("random forest", "随机森林"),
  term("eigenvalue", "特征值"),
  term("eigenvector", "特征向量"),
  term("covariance matrix", "协方差矩阵"),
  term("dimensionality reduction", "降维"),
];

export interface GlossaryPreset {
  id: string;
  version: number;
  label: string;
  terms: GlossaryTerm[];
}

const CELLULAR_NETWORK_PRESET: GlossaryPreset = {
  id: "cellular-networks",
  version: 1,
  label: "蜂窝网络推荐词表",
  terms: CELLULAR_NETWORK_GLOSSARY,
};

const MACHINE_LEARNING_PRESET: GlossaryPreset = {
  id: "machine-learning-applications",
  version: 1,
  label: "机器学习推荐词表",
  terms: MACHINE_LEARNING_GLOSSARY,
};

export function recommendedGlossaryPreset(
  course: Pick<Course, "code" | "name" | "description">,
): GlossaryPreset | null {
  const signature = `${course.code} ${course.name} ${course.description}`.toLowerCase();
  if (course.code.trim().toUpperCase() === "CEG5104"
    || /cellular\s+networks?|蜂窝网络/.test(signature)
  ) return CELLULAR_NETWORK_PRESET;
  if (course.code.trim().toUpperCase() === "CEG5301"
    || /machine\s+learning|机器学习/.test(signature)
  ) return MACHINE_LEARNING_PRESET;
  return null;
}

export function mergeGlossaryTerms(
  existing: GlossaryTerm[],
  suggested: GlossaryTerm[],
): { terms: GlossaryTerm[]; added: number } {
  const seen = new Set(
    existing
      .map((item) => item.english.trim().toLocaleLowerCase())
      .filter(Boolean),
  );
  const additions = suggested
    .filter((item) => {
      const key = item.english.trim().toLocaleLowerCase();
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .map((item) => ({ ...item }));
  return { terms: [...existing, ...additions], added: additions.length };
}
